"""Add Start Table

Revision ID: 17bb0b46a25d
Revises: 
Create Date: 2023-12-23 03:13:38.132008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bb0b46a25d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('resitred_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_to_level', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('array_charac', sa.JSON(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('is_equip', sa.Boolean(), nullable=False),
    sa.Column('buf', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('helm', sa.Integer(), nullable=True),
    sa.Column('chest', sa.Integer(), nullable=True),
    sa.Column('legs', sa.Integer(), nullable=True),
    sa.Column('arm', sa.Integer(), nullable=True),
    sa.Column('weapon_1', sa.Integer(), nullable=True),
    sa.Column('weapon_2', sa.Integer(), nullable=True),
    sa.Column('amulet', sa.Integer(), nullable=True),
    sa.Column('ring_1', sa.Integer(), nullable=True),
    sa.Column('ring_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amulet'], ['items.id'], ),
    sa.ForeignKeyConstraint(['arm'], ['items.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['chest'], ['items.id'], ),
    sa.ForeignKeyConstraint(['helm'], ['items.id'], ),
    sa.ForeignKeyConstraint(['legs'], ['items.id'], ),
    sa.ForeignKeyConstraint(['ring_1'], ['items.id'], ),
    sa.ForeignKeyConstraint(['ring_2'], ['items.id'], ),
    sa.ForeignKeyConstraint(['weapon_1'], ['items.id'], ),
    sa.ForeignKeyConstraint(['weapon_2'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear')
    op.drop_table('items')
    op.drop_table('characteristics')
    op.drop_table('token')
    op.drop_table('character')
    op.drop_table('user')
    # ### end Alembic commands ###
