"""Add actual_xp

Revision ID: 8b8d1be75617
Revises: f6e2f3a7e08f
Create Date: 2024-02-29 02:31:34.942133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8d1be75617'
down_revision: Union[str, None] = 'f6e2f3a7e08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('actual_xp', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'actual_xp')
    # ### end Alembic commands ###
