"""Add Start Table

Revision ID: e88510fe3bc9
Revises: 0c0a67074eeb
Create Date: 2024-03-01 19:40:20.778537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88510fe3bc9'
down_revision: Union[str, None] = '0c0a67074eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enemy', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('enemylist', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enemylist', 'xp')
    op.drop_column('enemy', 'xp')
    # ### end Alembic commands ###
