"""Add List of Types-Items and List of Bufs

Revision ID: 805ef33781c6
Revises: e88510fe3bc9
Create Date: 2024-03-03 03:13:06.491251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '805ef33781c6'
down_revision: Union[str, None] = 'e88510fe3bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listbufs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ratebufs', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listtypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('firstname', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('secondname', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rateprice', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listtypes')
    op.drop_table('listbufs')
    # ### end Alembic commands ###
