"""Retur to normal

Revision ID: ad59a91878ba
Revises: eecd2ac468cb
Create Date: 2023-12-31 15:37:49.192128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad59a91878ba'
down_revision: Union[str, None] = 'eecd2ac468cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_to_level', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('attack_point', sa.Integer(), nullable=False),
    sa.Column('defend', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'characteristics', 'character', ['character_id'], ['id'])
    op.create_foreign_key(None, 'gear', 'character', ['character_id'], ['id'])
    op.create_foreign_key(None, 'items', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'gear', type_='foreignkey')
    op.drop_constraint(None, 'characteristics', type_='foreignkey')
    op.drop_table('character')
    # ### end Alembic commands ###
